GET http://localhost:8080/api/tasks

###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Learn Spring Boot2",
  "description": "Understand Controllers and Services2"
}

###